"""empty message

Revision ID: 00482daff35a
Revises: e910c026beaf
Create Date: 2026-07-09 21:08:31.350345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00482daff35a'
down_revision = 'e910c026beaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('fee_year', sa.Integer(), nullable=False),
    sa.Column('fee_month', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building', 'unit_number', 'fee_year', 'fee_month', name='unique_unit_debt_period')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_debt')
    # ### end Alembic commands ###
