"""empty message

Revision ID: 0455d9725c86
Revises: d91c9e2c6fa4
Create Date: 2026-07-07 00:41:43.572792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0455d9725c86'
down_revision = 'd91c9e2c6fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_bill_attachment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_bill', schema=None) as batch_op:
        batch_op.drop_column('water_bill_attachment')

    # ### end Alembic commands ###
