"""empty message

Revision ID: 21355bf47225
Revises: 0455d9725c86
Create Date: 2026-07-07 15:01:35.781035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21355bf47225'
down_revision = '0455d9725c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_bill', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('bill_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_bill', schema=None) as batch_op:
        batch_op.drop_column('bill_number')

    # ### end Alembic commands ###
