"""empty message

Revision ID: 45358dd7deb7
Revises: 75812d5991d5
Create Date: 2026-07-07 22:45:26.359684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45358dd7deb7'
down_revision = '75812d5991d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_number', sa.Integer(), nullable=False),
    sa.Column('emission_date', sa.Date(), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('water_usage_total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('electricity_usage_common_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('administration_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('security_staff_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cleaning_staff_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('elevator_maintenance_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('miscellaneous_expenses_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preventive_maintenance_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('penalty_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_fees')
    # ### end Alembic commands ###
