"""empty message

Revision ID: 5ef9758baca8
Revises: db576ecfed4f
Create Date: 2026-07-10 04:08:57.106937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef9758baca8'
down_revision = 'db576ecfed4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electricity_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('electricity_usage_total_cost_1', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('electricity_usage_total_cost_2', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electricity_bills', schema=None) as batch_op:
        batch_op.drop_column('electricity_usage_total_cost_2')
        batch_op.drop_column('electricity_usage_total_cost_1')

    # ### end Alembic commands ###
