"""empty message

Revision ID: 739bd6bcd0ec
Revises: a6d4e533fa7a
Create Date: 2026-07-07 02:47:24.572624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739bd6bcd0ec'
down_revision = 'a6d4e533fa7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
