"""empty message

Revision ID: 818e256b0489
Revises: 
Create Date: 2026-07-15 18:20:31.694980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818e256b0489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('additional_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('supply_number', sa.String(length=50), nullable=False),
    sa.Column('supply_number_2', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('expense_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operation_number', sa.String(length=50), nullable=True),
    sa.Column('description_detail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_number', sa.Integer(), nullable=False),
    sa.Column('emission_date', sa.Date(), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('water_usage_total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('electricity_usage_common_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('administration_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('security_staff_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cleaning_staff_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('elevator_maintenance_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('miscellaneous_expenses_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preventive_maintenance_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('penalty_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('fee_year', sa.Integer(), nullable=False),
    sa.Column('fee_month', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building', 'unit_number', 'fee_year', 'fee_month', name='unique_unit_debt_period')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.String(length=10), nullable=True),
    sa.Column('rol', sa.String(length=100), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('water_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('supply_number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('water_usage_total_m3', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('water_usage_total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('water_bill_attachment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_usage_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('supply_number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('meter_reading_m3', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('meter_reading_photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('id_owner', sa.Integer(), nullable=True),
    sa.Column('id_resident', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_owner'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_resident'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_number')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('operation_number', sa.Integer(), nullable=True),
    sa.Column('id_unit', sa.Integer(), nullable=False),
    sa.Column('voucher', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['id_unit'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income')
    op.drop_table('unit')
    op.drop_table('water_usage_unit')
    op.drop_table('water_bill')
    op.drop_table('user')
    op.drop_table('unit_debt')
    op.drop_table('maintenance_fees')
    op.drop_table('expenses')
    op.drop_table('electricity_bills')
    op.drop_table('budget')
    # ### end Alembic commands ###
