"""empty message

Revision ID: 82ba3fdabfc4
Revises: f1e57acacdf8
Create Date: 2026-07-06 21:03:51.847027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ba3fdabfc4'
down_revision = 'f1e57acacdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('operation_number', sa.Integer(), nullable=True),
    sa.Column('id_unit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_unit'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income')
    # ### end Alembic commands ###
