"""empty message

Revision ID: 919c1d9c6628
Revises: ee6a863f6457
Create Date: 2026-07-07 00:10:57.036933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919c1d9c6628'
down_revision = 'ee6a863f6457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage_unit', schema=None) as batch_op:
        batch_op.alter_column('period_start',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('period_end',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage_unit', schema=None) as batch_op:
        batch_op.alter_column('period_end',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('period_start',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
