"""empty message

Revision ID: 9768708cd587
Revises: cd3d691bf20b
Create Date: 2026-07-14 18:14:40.882644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9768708cd587'
down_revision = 'cd3d691bf20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electricity_bill')
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['receipt_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('receipt_number')

    op.create_table('electricity_bill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('building', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('supply_number_1', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('supply_number_2', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('electricity_usage_total_cost_1', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('electricity_usage_total_cost_2', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('electricity_bill_pkey'))
    )
    # ### end Alembic commands ###
