"""empty message

Revision ID: a6d4e533fa7a
Revises: d3ad3f62327a
Create Date: 2026-07-06 23:00:33.883676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d4e533fa7a'
down_revision = 'd3ad3f62327a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('supply_number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('water_usage_total_m3', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('water_usage_total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_bill')
    # ### end Alembic commands ###
