"""empty message

Revision ID: b4730646c7e3
Revises: 5ef9758baca8
Create Date: 2026-07-10 22:59:50.579228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4730646c7e3'
down_revision = '5ef9758baca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricity_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('supply_number_1', sa.String(length=50), nullable=False),
    sa.Column('supply_number_2', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('electricity_usage_total_cost_1', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('electricity_usage_total_cost_2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('electricity_bills', schema=None) as batch_op:
        batch_op.drop_column('electricity_usage_total_cost_1')
        batch_op.drop_column('electricity_usage_total_cost_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electricity_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('electricity_usage_total_cost_2', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('electricity_usage_total_cost_1', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))

    op.drop_table('electricity_bill')
    # ### end Alembic commands ###
