"""empty message

Revision ID: cc824c33a4f4
Revises: 82ba3fdabfc4
Create Date: 2026-07-06 21:10:33.482627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc824c33a4f4'
down_revision = '82ba3fdabfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.alter_column('id_owner',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_resident',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.alter_column('id_resident',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_owner',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
