"""empty message

Revision ID: d1328d011d41
Revises: 919c1d9c6628
Create Date: 2026-07-07 00:20:11.665902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1328d011d41'
down_revision = '919c1d9c6628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage_unit', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
