"""empty message

Revision ID: d91c9e2c6fa4
Revises: d1328d011d41
Create Date: 2026-07-07 00:30:49.772633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91c9e2c6fa4'
down_revision = 'd1328d011d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meter_reading_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage_unit', schema=None) as batch_op:
        batch_op.drop_column('meter_reading_photo')

    # ### end Alembic commands ###
