"""empty message

Revision ID: e910c026beaf
Revises: 45358dd7deb7
Create Date: 2026-07-07 23:00:00.065856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e910c026beaf'
down_revision = '45358dd7deb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('expense_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operation_number', sa.String(length=50), nullable=True),
    sa.Column('description_detail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
