"""empty message

Revision ID: f1e57acacdf8
Revises: 85f6490a96a5
Create Date: 2026-07-06 17:27:36.538874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e57acacdf8'
down_revision = '85f6490a96a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=False),
    sa.Column('id_owner', sa.Integer(), nullable=False),
    sa.Column('id_resident', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_owner'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_resident'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.drop_table('unit')
    # ### end Alembic commands ###
